####################
# mindmap - Create #
####################
curl -X POST http://localhost:5000/mindmap  -H 'content-type: application/json' -d '{"id": "root_id"}'

##############
# Leaf - Add #
##############
curl -X POST http://127.0.0.1:5000/leaf \
  -H 'content-type: application/json' \
  -d '{
    "id": "root_id",
    "path": "I/like/big/potatoes",
    "text": "Because reasons"
}'

###############
# Leaf - Read #
###############
curl -X GET http://127.0.0.1:5000/leaf \
  -H 'content-type: application/json' \
  -d '{
    "id": "root_id",
    "path": "I/like/potatoes"
}'

##########################
# mindmap - Pretty print #
##########################
curl -X GET http://localhost:5000/mindmap  -H 'content-type: application/json' -d '{"id": "root_id"}'
